all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: 44.246.194.104
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/aws

    database:
      hosts:
        server-two:
          ansible_host: 34.221.113.168
          ansible_user: rocky
          ansible_ssh_private_key_file: ~/.ssh/aws
